-- MySQL Script generated by MySQL Workbench
-- Tue Aug 31 14:58:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema csc648_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csc648_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csc648_db` DEFAULT CHARACTER SET latin1 ;
USE `csc648_db` ;

-- -----------------------------------------------------
-- Table `csc648_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc648_db`.`category` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `csc648_db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc648_db`.`status` (
  `status_id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `csc648_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc648_db`.`user` (
  `name` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` CHAR(60) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `issues` INT(11) NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `csc648_db`.`issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc648_db`.`issue` (
  `issue_id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `photo` MEDIUMTEXT NULL,
  `location` VARCHAR(45) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `status_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `time_stamp` DATETIME NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`issue_id`),
  INDEX `fk_issue_category_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_issue_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_issue_status1_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_issue_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `csc648_db`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issue_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `csc648_db`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issue_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `csc648_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `csc648_db`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc648_db`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comment` MEDIUMTEXT NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `issue_id` INT(11) NULL DEFAULT NULL,
  `time_stamp` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_issue1_idx` (`issue_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_issue1`
    FOREIGN KEY (`issue_id`)
    REFERENCES `csc648_db`.`issue` (`issue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
